# Generated by Django 4.2.8 on 2026-02-06 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'Agência',
                'verbose_name_plural': 'Agências',
            },
        ),
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
            },
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Bordero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_envio', models.DateField(blank=True, null=True)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='novo', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('quantidade_titulos', models.IntegerField(default=0)),
                ('observacoes', models.TextField(blank=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factoring_app.banco')),
            ],
            options={
                'verbose_name': 'Bordero',
                'verbose_name_plural': 'Borderos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('tipo_pessoa', models.CharField(choices=[('pf', 'Pessoa Física'), ('pj', 'Pessoa Jurídica')], max_length=2)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=10)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ativo', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('numero_sequencial', models.AutoField(primary_key=True, serialize=False)),
                ('numero_documento', models.CharField(max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_vencimento', models.DateField()),
                ('data_emissao', models.DateField()),
                ('data_desconto', models.DateField(blank=True, null=True)),
                ('taxa_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado'), ('devolvido', 'Devolvido')], default='pendente', max_length=20)),
                ('data_ocorrencia', models.DateField(blank=True, null=True)),
                ('instrucao', models.TextField(blank=True)),
                ('bordero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='factoring_app.bordero')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True)),
                ('descricao', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('nacional', 'Nacional'), ('estadual', 'Estadual'), ('municipal', 'Municipal')], max_length=20)),
                ('estado', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa'), ('informativa', 'Informativa')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
        migrations.CreateModel(
            name='ParametrosGerais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('valor', models.TextField()),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('numero', 'Número'), ('data', 'Data'), ('moeda', 'Moeda')], max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Parâmetro Geral',
                'verbose_name_plural': 'Parâmetros Gerais',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('operador', 'Operador'), ('visualizador', 'Visualizador')], default='operador', max_length=20)),
                ('permissao_incluir', models.BooleanField(default=False)),
                ('permissao_atualizar', models.BooleanField(default=False)),
                ('permissao_excluir', models.BooleanField(default=False)),
                ('permissao_consulta', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permissão do Usuário',
                'verbose_name_plural': 'Permissões do Usuário',
            },
        ),
        migrations.CreateModel(
            name='Sacado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sacados', to='factoring_app.cliente')),
            ],
            options={
                'verbose_name': 'Sacado',
                'verbose_name_plural': 'Sacados',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id_pagamento', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_pagamento', models.CharField(choices=[('boleto', 'Boleto'), ('cheque', 'Cheque'), ('transferencia', 'Transferência'), ('dinheiro', 'Dinheiro'), ('cartao', 'Cartão')], max_length=20)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_pagamento', models.DateField(auto_now_add=True)),
                ('observacoes', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='factoring_app.documento')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.CreateModel(
            name='LogOperacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_operacao', models.CharField(choices=[('criar', 'Criar'), ('atualizar', 'Atualizar'), ('deletar', 'Deletar'), ('consultar', 'Consultar'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('tabela', models.CharField(max_length=100)),
                ('id_registro', models.IntegerField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Operação',
                'verbose_name_plural': 'Logs de Operação',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacaoBordero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_liquidacao', models.DateField(auto_now_add=True)),
                ('valor_total_recebido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('juros_cobrados', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacoes', models.TextField(blank=True)),
                ('bordero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='liquidacao', to='factoring_app.bordero')),
            ],
            options={
                'verbose_name': 'Liquidação de Bordero',
                'verbose_name_plural': 'Liquidações de Borderos',
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='ocorrencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='factoring_app.ocorrencia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='sacado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factoring_app.sacado'),
        ),
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factoring_app.tipodocumento'),
        ),
        migrations.CreateModel(
            name='ContaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo_conta', models.CharField(choices=[('corrente', 'Corrente'), ('poupanca', 'Poupança'), ('investimento', 'Investimento')], max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('ativa', models.BooleanField(default=True)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='factoring_app.agencia')),
            ],
            options={
                'verbose_name': 'Conta Bancária',
                'verbose_name_plural': 'Contas Bancárias',
                'unique_together': {('agencia', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('emitente', models.CharField(max_length=150)),
                ('beneficiario', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('data_emissao', models.DateField()),
                ('data_compensacao', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('emitido', 'Emitido'), ('compensado', 'Compensado'), ('devolvido', 'Devolvido'), ('cancelado', 'Cancelado')], default='emitido', max_length=20)),
                ('motivo_devolucao', models.CharField(blank=True, max_length=200)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('conta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factoring_app.contabancaria')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
            },
        ),
        migrations.AddField(
            model_name='bordero',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='factoring_app.cliente'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencias', to='factoring_app.banco'),
        ),
        migrations.AlterUniqueTogether(
            name='agencia',
            unique_together={('banco', 'numero')},
        ),
    ]
